swagger: "2.0"
info:
  description: "MeetingBook is a standalone Calendly like application to manage appointments and share them with guests so that they can book the appointment."
  version: "1.0.0"  
  title: "MeetingBook"
  license:
    name: "MIT"
    url: "https://opensource.org/licenses/MIT"
externalDocs:
  description: "Project Source"
  url: "https://github.com/meetingbook/meetingbook"
host: "localhost:5000"
basePath: "/"
schemes:
- "https"
- "http"
securityDefinitions:
  basic_auth:
    type: basic
paths:
  /admin:
    get:
      description: Test API endpoint
      parameters:
        - in: header
          name: Authorization
          type: string
          required: true
          description: |
            Authorization header contains the Basic word followed by a space 
            and a base64-encoded username:password string.
            For example, a header containing the "admin" and "Pyth0n" credentials would be encoded as "Authorization: Basic YWRtaW46UHl0aDBu"
      security:
        - basic_auth: []
      produces:
      - "application/json"
      responses:
        "200":
          description: "Successful admin request"
  /login:
    get:
      parameters:
        - in: header
          name: Authorization
          type: string
          required: true
          description: |
            Authorization header contains the Basic word followed by a space 
            and a base64-encoded username:password string.
            For example, a header containing the demo and p@55w0rd credentials 
            would be encoded as "Authorization: Basic ZGVtbzpwQDU1dzByZA=="
      produces:
      - "application/json"
      responses:
        "200":
          description: "Successful login"
        "401":
          description: "Unauthorized"
  /schedule:
    get:
      parameters:
        - in: query
          name: filter
          type: string
          description: |
            Filter "free or booking". 
            To get **free** slots: `/schedule/filter=status="free"` 
            
            To get **booked** slots: `/schedule/filter=status="booking"`
        - in: query
          name: week
          type: string
          description: |
            To get slots for a given week.
            `/schedule/week=2021-01-01`
            
            To get booking slots for a given week.
            `/schedule/week=2021-01-01&filter=status="booking"`
        - in: query
          name: day
          type: string
          description: |
            To get slots for a given day.
            `/schedule/day=2021-01-01`
      responses:
        "200":
          description: "Successful operation"
          schema:
            $ref: "#/definitions/Schedule"
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
      security:
        - basic_auth: []
  /bookings/{booking_id}:
    get:
      parameters:
        - in: path
          name: booking_id
          type: string
          description: |
            Receives the `"booking_id"` of the booked slot, and sends a response with information about users booked this slot(name, email, topic)
              `/booking/{booking_id}`
          required: true  
      responses:
        "200":
          description: "Successful request"
          schema:
            $ref: "#/definitions/Booking"
definitions:
  Schedule:
    type: "object"
    properties:
      slots:
        type: array
        items:
          $ref: "#/definitions/Slot"
  Admin:
    type: "object"
    required:
      - id
      - email
      - password
      - avatar
    properties:
      id:
        type: "integer"
        format: "int64"
      email:
        type: "string"
      password:
        type: "string"
        description: "Hashed and salted password"
      avatar:
        type: "string"
        format: "base64"
        description: "Admins avatar"
  Slot:
    type: "object"
    required:
      - id
      - start
      - end
      - booking_id
    properties:
      id:
        type: "integer"
        format: "int64"
      start:
        type: "string"
        format: "date-time"
        description: "Start of the slot. Defined as Datetime string in ISO 8601 https://en.wikipedia.org/wiki/ISO_8601"
      end:
        type: "string"
        format: "date-time"
        description: "End of the slot. Defined as Datetime string in ISO 8601 https://en.wikipedia.org/wiki/ISO_8601"
      booking_id: 
        type: "integer"
        format: "int64"
        description: "ID reference to booking"
  Booking:
    type: "object"
    required:
      - id
      - guest_name
      - guest_email
    properties:
      id:
        type: "integer"
        format: "int64"
      guest_name:
        type: "string"
        description: "Guest name who makes a booking"
      guest_email:
        type: "string"
        description: "Guest email who makes a booking"
      topic:
        type: "string"
        description: "Topic to discuss"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"