"""empty message

Revision ID: 1ac6e09c06de
Revises: b405d05fd250
Create Date: 2021-10-01 21:06:30.402303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ac6e09c06de'
down_revision = 'b405d05fd250'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BookingSettings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('duration', sa.PickleType(), nullable=False),
    sa.Column('start_time', sa.PickleType(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['AdminInfo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('BookingSettings')
    # ### end Alembic commands ###
