"""empty message

Revision ID: 28c1a44ba56d
Revises: 8187e8ea9e37
Create Date: 2021-09-03 14:03:41.753541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28c1a44ba56d'
down_revision = '8187e8ea9e37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Slots', sa.Column('end_interval', sa.String(length=50), nullable=False))
    op.add_column('Slots', sa.Column('admin_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'Slots', ['end_interval'])
    op.create_foreign_key(None, 'Slots', 'AdminInfo', ['admin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Slots', type_='foreignkey')
    op.drop_constraint(None, 'Slots', type_='unique')
    op.drop_column('Slots', 'admin_id')
    op.drop_column('Slots', 'end_interval')
    # ### end Alembic commands ###
