"""empty message

Revision ID: 8187e8ea9e37
Revises: cfe9f0ee23c4
Create Date: 2021-09-03 13:55:25.508220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8187e8ea9e37'
down_revision = 'cfe9f0ee23c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AdminInfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('psw', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('BookingInfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=500), nullable=False),
    sa.Column('topic', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_interval', sa.String(length=50), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['BookingInfo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('start_interval')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Slots')
    op.drop_table('BookingInfo')
    op.drop_table('AdminInfo')
    # ### end Alembic commands ###
