"""empty message

Revision ID: acee791c3ef2
Revises: e584a74da452
Create Date: 2021-10-28 13:29:33.853227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acee791c3ef2'
down_revision = 'e584a74da452'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('BookingInfo', sa.Column('uuid', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('BookingInfo', 'uuid')
    # ### end Alembic commands ###
