"""empty message

Revision ID: b0cc4db3108e
Revises: bf18bde4baf2
Create Date: 2021-08-17 16:24:45.844125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0cc4db3108e'
down_revision = 'bf18bde4baf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_interval', sa.String(length=50), nullable=True),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking_info.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('start_interval')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slots')
    # ### end Alembic commands ###
