"""empty message

Revision ID: b405d05fd250
Revises: 
Create Date: 2021-09-07 14:02:30.503405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b405d05fd250'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AdminInfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('psw', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('BookingInfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=500), nullable=False),
    sa.Column('topic', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_interval', sa.String(length=50), nullable=False),
    sa.Column('end_interval', sa.String(length=50), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['AdminInfo.id'], ),
    sa.ForeignKeyConstraint(['booking_id'], ['BookingInfo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('start_interval', 'end_interval', 'admin_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Slots')
    op.drop_table('BookingInfo')
    op.drop_table('AdminInfo')
    # ### end Alembic commands ###
