"""empty message

Revision ID: bd4f74cd5691
Revises: b405d05fd250
Create Date: 2021-10-04 20:51:44.451529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd4f74cd5691'
down_revision = 'b405d05fd250'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BookingSettings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('duration', sa.JSON(), nullable=False),
    sa.Column('start_time', sa.JSON(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['AdminInfo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('BookingSettings')
    # ### end Alembic commands ###
