"""empty message

Revision ID: cfe9f0ee23c4
Revises: 728725157886
Create Date: 2021-09-03 13:51:48.780790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfe9f0ee23c4'
down_revision = '728725157886'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('AdminInfo')
    op.drop_table('BookingInfo')
    op.drop_table('Slots')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Slots',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('start_interval', sa.VARCHAR(length=50), nullable=False),
    sa.Column('booking_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['BookingInfo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('start_interval')
    )
    op.create_table('BookingInfo',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('email', sa.VARCHAR(length=500), nullable=False),
    sa.Column('topic', sa.VARCHAR(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('AdminInfo',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=50), nullable=False),
    sa.Column('psw', sa.VARCHAR(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###
