"""empty message

Revision ID: e36a740837a6
Revises: bd4f74cd5691
Create Date: 2021-10-07 22:53:11.601915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e36a740837a6'
down_revision = 'bd4f74cd5691'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link_id', sa.String(length=100), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['AdminInfo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Links')
    # ### end Alembic commands ###
