"""empty message

Revision ID: e584a74da452
Revises: bd4f74cd5691
Create Date: 2021-10-13 15:51:29.176090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e584a74da452'
down_revision = 'bd4f74cd5691'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link_id', sa.String(length=100), nullable=False),
    sa.Column('valid_until', sa.String(length=50), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['AdminInfo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Links')
    # ### end Alembic commands ###
